sudo tee /etc/vpnc/fortigate.conf > /dev/null <<'EOF'
IPSec gateway 203.0.113.3
IPSec ID vpn
IPSec secret Lab12345
IKE Authmode psk
Xauth username vpnuser
Xauth password Lab12345
IKE DH Group dh5
Enable weak encryption
Enable weak authentication
NAT Traversal Mode natt
EOF
